# Generated by Django 4.2.18 on 2025-02-19 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_user_is_staff_user_last_login_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_view_project', 'Can view project'), ('can_add_project', 'Can add project'), ('can_edit_project', 'Can edit project'), ('can_delete_project', 'Can delete project')]},
        ),
    ]
