# Generated by Django 4.2.19 on 2025-02-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='login_time',
            field=models.DateTimeField(),
        ),
    ]
