# Generated by Django 4.2.18 on 2025-02-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_projectcomment_projectupdate_remove_taskupdate_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
