# Generated by Django 4.2.19 on 2025-03-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignrequest',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
