# Generated by Django 4.2.19 on 2025-03-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_resignrequest_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignrequest',
            name='additional_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resignrequest',
            name='compensation_satisfaction',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resignrequest',
            name='growth_opportunities',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resignrequest',
            name='manager_experience',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resignrequest',
            name='overall_satisfaction',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resignrequest',
            name='reason_for_leaving',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resignrequest',
            name='recommend_company',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='resignrequest',
            name='work_environment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resignrequest',
            name='work_life_balance',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
