# Generated by Django 4.2.19 on 2025-03-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_resignrequest_additional_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignrequest',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
