# Generated by Django 4.2.19 on 2025-03-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_resignrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
