# Generated by Django 4.2.19 on 2025-03-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_resignrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignrequest',
            name='hr_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resignrequest',
            name='manager_comments',
            field=models.TextField(blank=True),
        ),
    ]
