# Generated by Django 4.2.18 on 2025-03-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_booking_room_guest_booking_room_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_out',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='description',
            new_name='amenities',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2025-01-01T00:00:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('room', 'start_time', 'end_time')},
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
