# Generated by Django 4.2.18 on 2025-03-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_rename_check_in_booking_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
