# Generated by Django 4.2.18 on 2025-03-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('IN', 'India'), ('USA', 'USA'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia')], default='India', max_length=50),
        ),
    ]
