# Generated by Django 4.2.18 on 2025-03-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('IN', 'IN'), ('USA', 'USA'), ('UK', 'UK'), ('CA', 'CA'), ('AU', 'AU')], default='India', max_length=50),
        ),
    ]
