# Generated by Django 4.2.18 on 2025-03-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hr_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='manager_comments',
            field=models.TextField(blank=True),
        ),
    ]
