# Generated by Django 4.2.18 on 2025-03-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_room_hr_comments_room_manager_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='hr_approved',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hr_comments',
        ),
        migrations.RemoveField(
            model_name='room',
            name='manager_comments',
        ),
    ]
