# Generated by Django 4.2.18 on 2025-04-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_finance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='salary',
        ),
        migrations.AddField(
            model_name='finance',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='finance',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='finance',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='finance',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='finance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20),
        ),
    ]
