# Generated by Django 4.2.18 on 2025-04-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_remove_finance_salary_finance_allowances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Finance', 'Finance')], default='Employee', max_length=50),
        ),
    ]
