# Generated by Django 4.2.18 on 2025-04-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Manager', 'Manager'), ('Employee', 'Employee')], default='Employee', max_length=50),
        ),
    ]
