# Generated by Django 4.2.18 on 2025-04-03 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_reimbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='approved_by_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
